name: bip21_bch_dart
description: Dart implementation of the BIP-21 Bitcoin Cash URI scheme
version: 1.0.0
author: videah <videah@selfish.systems>, RomitRadical<romitradical@protonmail.com>
repository: https://github.com/RomitRadical/bip21-bch-dart
homepage: https://github.com/RomitRadical/bip21-bch-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.0.0
