name: bip21
description: Dart implementation of the BIP-21 Bitcoin URI scheme
version: 1.0.0
author: videah <videah@selfish.systems>
repository: https://github.com/videah/bip21-dart
homepage: https://github.com/videah/bip21-dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: ^1.0.0
